/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const MessageCategory = IDL.Variant({
  'question' : IDL.Null,
  'other' : IDL.Null,
  'contentSuggestion' : IDL.Null,
  'featureRequest' : IDL.Null,
  'bugReport' : IDL.Null,
});
export const FeedbackMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Opt(IDL.Text),
  'email' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'timestamp' : Time,
  'category' : MessageCategory,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllFeedbackMessages' : IDL.Func(
      [],
      [IDL.Vec(FeedbackMessage)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitFeedback' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, MessageCategory],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const MessageCategory = IDL.Variant({
    'question' : IDL.Null,
    'other' : IDL.Null,
    'contentSuggestion' : IDL.Null,
    'featureRequest' : IDL.Null,
    'bugReport' : IDL.Null,
  });
  const FeedbackMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Opt(IDL.Text),
    'email' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'timestamp' : Time,
    'category' : MessageCategory,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllFeedbackMessages' : IDL.Func(
        [],
        [IDL.Vec(FeedbackMessage)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitFeedback' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Text, MessageCategory],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };